#!/bin/sh
# This file is automatically added by husky
# Please do not edit this file directly.

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

if [ -z "$HUSKY" ]; then
  HUSKY=1
  export HUSKY

  if [ "$0" = "$BASH_SOURCE" ]; then
    if command_exists run_with_husky; then
      run_with_husky "$@"
    else
      user_id=$(id -u)
      group_id=$(id -g)
      husky_dir=$(cd "$(dirname "$0")/.." && pwd)
      
      if [ "$user_id" = "$(stat -c '%u' "$husky_dir")" ] && [ "$group_id" = "$(stat -c '%g' "$husky_dir")" ]; then
        "$@"
      else
        echo "husky: permission denied (are you trying to run hooks from a different user?)"
        exit 1
      fi
    fi
  fi
fi
